name: Testing the Python code

on:
 push:
  branches:
   - main
jobs:
 build:
 
  runs-on: ubuntu-latest
  strategy:
   matrix:
    python-version: [ "3.11" ]
 
  steps:
   - uses: actions/checkout@v3
   - name: Set up Python ${{ matrix.python-version }}
     uses: actions/setup-python@v4
     with:
      python-version: ${{ matrix.python-version }}
   - name: Install dependencies
     run: |
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 style_check:
  needs: build
  runs-on: ubuntu-latest
  steps:
   - name: Lint with pycodestyle
     run: |
      pycodestyle tplab2 shop basket
 test:
  needs: style_check
  runs-on: ubuntu-latest
  steps:
   - name: Test with pytest
     run: |
      python manage.py test .\shop\tests\ .\basket\tests\